// Smoke tests for the Gran Fondo Badlands map.
// Asserts the configured artifacts (theme, geojson, profiles, turn lists,
// weather) are wired up and the per-distance metadata is internally
// consistent. Assumes `node build.js` has already been run; vitest does
// not invoke the build itself (Playwright config does that for e2e specs).

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname || __dirname, '..');
const MAP_DIR = join(ROOT, 'src', 'maps', 'gran-fondo-badlands');
const DATA_DIR = join(MAP_DIR, 'data');
const DIST_HTML = join(ROOT, 'dist', 'maps', 'gran-fondo-badlands', 'index.html');

describe('gran-fondo-badlands · theme + config', () => {
  it('theme exposes 4 distances each tied to a 1-loop assembly', () => {
    const theme = require(join(ROOT, 'src/themes/gran-fondo-badlands.js'));
    expect(theme.slug).toBe('gran-fondo-badlands');
    expect(theme.raceFormat.distances).toHaveLength(4);
    for (const d of theme.raceFormat.distances) {
      expect(d.assembly).toHaveLength(1);
      expect(d.assembly[0].loopId).toBe(d.id);
      expect(d.dinosaur).toBe(d.id);
      expect(typeof d.kilometers).toBe('number');
      expect(typeof d.runMiles).toBe('number');
      expect(d.color).toMatch(/^#[0-9A-Fa-f]{6}$/);
    }
  });

  it('each distance has matching course.geojson + profile.json', () => {
    for (const id of ['brontosaurus', 'trex', 'triceratops', 'velociraptor']) {
      expect(existsSync(join(DATA_DIR, id + '.geojson'))).toBe(true);
      expect(existsSync(join(DATA_DIR, id + '-profile.json'))).toBe(true);
    }
  });

  it('GPX-derived distances match the theme within 2%', () => {
    const theme = require(join(ROOT, 'src/themes/gran-fondo-badlands.js'));
    for (const d of theme.raceFormat.distances) {
      const fc = JSON.parse(readFileSync(join(DATA_DIR, d.id + '.geojson'), 'utf8'));
      const km = fc.features[0].properties.distance_km;
      const tol = d.kilometers * 0.02;
      expect(Math.abs(km - d.kilometers)).toBeLessThanOrEqual(tol);
    }
  });

  it('aid station spine has 8 entries with km values increasing', () => {
    const theme = require(join(ROOT, 'src/themes/gran-fondo-badlands.js'));
    const stns = theme.aidStations;
    expect(stns.length).toBe(8);
    for (let i = 1; i < stns.length; i++) {
      expect(stns[i].kilometer).toBeGreaterThan(stns[i - 1].kilometer);
    }
  });

  it('weather.json was generated for July 4 race day', () => {
    const wPath = join(DATA_DIR, 'weather.json');
    expect(existsSync(wPath)).toBe(true);
    const w = JSON.parse(readFileSync(wPath, 'utf8'));
    expect(w.raceDate).toBe('2026-07-04');
    expect(w.dailyAverages.length).toBeGreaterThanOrEqual(7);
    expect(w.riskSummary.heat).toBeDefined();
  });

  it('all 4 turn-by-turn lists were generated by the FSS pipeline', () => {
    for (const id of ['brontosaurus', 'trex', 'triceratops', 'velociraptor']) {
      const fc = JSON.parse(readFileSync(join(DATA_DIR, id + '-turns.geojson'), 'utf8'));
      expect(fc.type).toBe('FeatureCollection');
      expect(fc.features.length).toBeGreaterThan(5);
      // a meaningful share of turns should have OSM-resolved labels
      const named = fc.features.filter(f => f.properties.label).length;
      expect(named / fc.features.length).toBeGreaterThanOrEqual(0.6);
    }
  });
});

describe('gran-fondo-badlands · built HTML', () => {
  it('compiled HTML inlines all four loop datasets + dinosaur SVGs', () => {
    if (!existsSync(DIST_HTML)) {
      throw new Error('Run `node build.js` before testing.');
    }
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('var brontoData');
    expect(html).toContain('var trexData');
    expect(html).toContain('var triData');
    expect(html).toContain('var veloData');
    expect(html).toContain('DINO_SVGS');
    expect(html).toContain('AID_STATIONS_ALL');
  });

  it('compiled HTML has all 4 distance picker chips', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('data-race="brontosaurus"');
    expect(html).toContain('data-race="trex"');
    expect(html).toContain('data-race="triceratops"');
    expect(html).toContain('data-race="velociraptor"');
  });

  it('compiled HTML applies the rust brand color', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('#A84D24');
  });
});
