// Smoke tests for the Pocantico Hills Marathon & Half Marathon map.
//
// Asserts the configured artifacts (theme, geojson, profiles, turn
// lists, weather) are wired up and the per-distance metadata is
// internally consistent. Assumes `node build.js` has already been
// run; vitest does not invoke the build itself.

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname || __dirname, '..');
const MAP_DIR = join(ROOT, 'src', 'maps', 'pocantico-hills');
const DATA_DIR = join(MAP_DIR, 'data');
const DIST_HTML = join(ROOT, 'dist', 'maps', 'pocantico-hills', 'index.html');

describe('pocantico-hills · theme + config', () => {
  it('theme exposes 2 distances each tied to a 1-loop assembly', () => {
    const theme = require(join(ROOT, 'src/themes/pocantico-hills.js'));
    expect(theme.slug).toBe('pocantico-hills');
    expect(theme.raceFormat.distances).toHaveLength(2);
    for (const d of theme.raceFormat.distances) {
      expect(d.assembly).toHaveLength(1);
      expect(d.assembly[0].loopId).toBe(d.id);
      expect(typeof d.runMiles).toBe('number');
      expect(d.color).toMatch(/^#[0-9A-Fa-f]{6}$/);
    }
  });

  it('uses miles as the display unit (US race)', () => {
    const theme = require(join(ROOT, 'src/themes/pocantico-hills.js'));
    expect(theme.displayUnits).toBe('mi');
  });

  it('each distance has matching course.geojson + profile.json + turns.geojson', () => {
    for (const id of ['marathon', 'half-marathon']) {
      expect(existsSync(join(DATA_DIR, id + '.geojson'))).toBe(true);
      expect(existsSync(join(DATA_DIR, id + '-profile.json'))).toBe(true);
      expect(existsSync(join(DATA_DIR, id + '-turns.geojson'))).toBe(true);
    }
  });

  it('GPX-derived distances match the theme within 2%', () => {
    const theme = require(join(ROOT, 'src/themes/pocantico-hills.js'));
    for (const d of theme.raceFormat.distances) {
      const fc = JSON.parse(readFileSync(join(DATA_DIR, d.id + '.geojson'), 'utf8'));
      const mi = fc.features[0].properties.distance_mi;
      const tol = d.runMiles * 0.02;
      expect(Math.abs(mi - d.runMiles)).toBeLessThanOrEqual(tol);
    }
  });

  it('aid station spine has 9 entries (8 on-course + Finish) with mile values increasing', () => {
    const theme = require(join(ROOT, 'src/themes/pocantico-hills.js'));
    const stns = theme.aidStations;
    expect(stns.length).toBe(9);
    for (let i = 1; i < stns.length; i++) {
      expect(stns[i].mile).toBeGreaterThan(stns[i - 1].mile);
    }
    // Last entry is the explicit Finish at Rockwood Hall — its
    // mile value equals the marathon's total length, and the
    // renderer auto-collapses it onto the start GL symbol.
    expect(stns[stns.length - 1].name).toMatch(/Finish/i);
  });

  it('aid stations carry both mile and kilometer for schema parity', () => {
    const theme = require(join(ROOT, 'src/themes/pocantico-hills.js'));
    for (const s of theme.aidStations) {
      expect(typeof s.mile).toBe('number');
      expect(typeof s.kilometer).toBe('number');
      // Sanity: kilometer / 0.621371 ≈ mile
      const computedMi = s.kilometer * 0.621371;
      expect(Math.abs(computedMi - s.mile)).toBeLessThan(0.5);
    }
  });

  it('marathon visits all 8 aid stations + finish; half-marathon visits 4 shared stations + finish', () => {
    const theme = require(join(ROOT, 'src/themes/pocantico-hills.js'));
    const m = theme.raceFormat.distances.find(d => d.id === 'marathon');
    const h = theme.raceFormat.distances.find(d => d.id === 'half-marathon');
    // Index 8 is the Rockwood Hall Finish (auto-collapsed onto the
    // start by the renderer, but listed so the finish marker is
    // routed through the same code path as gran-fondo-badlands).
    expect(m.aidStations).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8]);
    expect(h.aidStations).toEqual([0, 1, 6, 7, 8]);
  });

  it('race day is November 7, 2026 — Saturday', () => {
    const theme = require(join(ROOT, 'src/themes/pocantico-hills.js'));
    expect(theme.raceDay.date).toBe('2026-11-07');
    expect(new Date(theme.raceDay.date + 'T12:00:00').getUTCDay()).toBe(6); // Saturday
  });

  it('weather.json was generated for the November 7 race day', () => {
    const wPath = join(DATA_DIR, 'weather.json');
    expect(existsSync(wPath)).toBe(true);
    const w = JSON.parse(readFileSync(wPath, 'utf8'));
    expect(w.raceDate).toBe('2026-11-07');
    expect(w.dailyAverages.length).toBeGreaterThanOrEqual(7);
    expect(w.riskSummary.heat).toBeDefined();
    // Mid-November in Westchester County → heat stress should be 'low'
    expect(w.riskSummary.heat.level).toBe('low');
  });

  it('turn-by-turn lists were generated by the FSS pipeline with named targets', () => {
    for (const id of ['marathon', 'half-marathon']) {
      const fc = JSON.parse(readFileSync(join(DATA_DIR, id + '-turns.geojson'), 'utf8'));
      expect(fc.type).toBe('FeatureCollection');
      expect(fc.features.length).toBeGreaterThanOrEqual(10);
      // OSM enrichment hit 97-98% on first run — keep the gate at 0.85
      // so a GPX swap that silently degrades naming breaks the build.
      const named = fc.features.filter(f => f.properties.label).length;
      expect(named / fc.features.length).toBeGreaterThanOrEqual(0.85);
    }
  });

  it('typography pairs Noticia Text + Lato — both free Google Fonts', () => {
    const theme = require(join(ROOT, 'src/themes/pocantico-hills.js'));
    expect(theme.type.display).toBe('Noticia Text');
    expect(theme.type.body).toBe('Lato');
    expect(theme.type.googleFontsHref).toContain('Noticia+Text');
    expect(theme.type.googleFontsHref).toContain('Lato');
  });
});

describe('pocantico-hills · built HTML', () => {
  it('compiled HTML inlines both loop datasets + turns + weather', () => {
    expect(existsSync(DIST_HTML)).toBe(true);
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('var marathonData');
    expect(html).toContain('var halfData');
    expect(html).toContain('LOOP_TURNS');
    expect(html).toContain('AID_STATIONS_ALL');
    expect(html).toContain('var DEFAULT_DISTANCE_ID');
  });

  it('compiled HTML has both distance picker chips with mile labels', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('data-race="marathon"');
    expect(html).toContain('data-race="half-marathon"');
    // The chip body shows the distance in miles + elevation in feet
    expect(html).toMatch(/26\.\d+ mi · \d+ ft/);
    expect(html).toMatch(/13\.\d+ mi · \d+ ft/);
  });

  it('compiled HTML applies the brand palette (ochre + olive + cream)', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('#c19434'); // ochre — primary brand
    expect(html).toContain('#34421e'); // deep olive — display ink
    expect(html).toContain('#f7f7f7'); // cream substrate
  });

  it('display unit is miles throughout — no km labels in user-facing UI', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain("var DISPLAY_UNITS = 'mi'");
    // Profile / directions / sim sections all render in miles
    expect(html).not.toContain("'<span class=\"sim-race-chip__km\">' + r.kilometers + ' km</span>'");
    expect(html).not.toContain("Avg pace: <strong>' + pace.toFixed(1) + ' km/h</strong>");
  });

  it('active-segment highlighting + snapped-turn precompute wired up', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('dir-active-segment');
    expect(html).toContain('dir-active-segment-halo');
    expect(html).toContain('dir-active-segment-line');
    expect(html).toContain('precomputeSnappedTurns');
    expect(html).toContain('SNAPPED_TURN_MILES');
    expect(html).toContain('setActiveTurnByRow');
    // Zoom-to-step preference persistence with race-specific key
    expect(html).toContain('pocanticoHills.zoomToStep');
    // And no leftover gran-fondo key
    expect(html).not.toContain('granFondoBadlands.zoomToStep');
  });

  it('foot-race simulator wiring is present (no dinosaur icons, mi units)', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('initSimulator');
    expect(html).toContain('relocateSimulator');
    expect(html).toContain('drawSimCourse');
    expect(html).toContain('drawSimTerrain');
    expect(html).toContain('sampleProfileAtMi');
    // Mi-based stat labels
    expect(html).toContain('Mile 0.0');
    // Default goal: 4h 48m (~11 min/mi for the marathon)
    expect(html).toContain('value="4"');
    expect(html).toContain('value="48"');
  });

  it('start/finish pennant is a GL symbol layer below place labels', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain("'hq-start'");
    expect(html).toContain('makeStartIconImage');
    expect(html).toContain('addHqStartLayer');
    expect(html).toContain('findFirstSymbolLayerId');
    expect(html).toContain("'icon-size': 0.7");
    expect(html).not.toContain('aid-marker--start');
  });

  it('editorial aid table renders mile header (not km) for this US race', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('aid-table__mile">Mile<');
    expect(html).toContain('Cutoff · mile');
    expect(html).not.toContain('Cutoff · km');
  });

  it('host attribution + cartography credit are intact', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain('pocanticohillsmarathon.com');
    expect(html).toContain('falsesummitstudio.com');
    expect(html).toContain('Saturday, November 7, 2026');
  });

  it('LOOP_IDS reflects pocantico-hills distances — no dinosaur leftovers', () => {
    // Regression guard: LOOP_IDS controls which loops addLoopLayers
    // iterates over. If this leaks dinosaur slugs from gran-fondo,
    // no course routes render at all (only the active-segment
    // highlight works). Seen + fixed during initial review.
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toContain("var LOOP_IDS = ['marathon', 'half-marathon']");
    expect(html).not.toMatch(/var LOOP_IDS = \['brontosaurus/);
  });

  it('active distance chip uses filled-block treatment (not just an inset ring)', () => {
    // Regression guard: the original active state was a 2px inset
    // ring of currentColor, which made the SVG numeral disappear
    // when its fill matched the ring color. Now the active state
    // is `background: currentColor` with cream label / numeral.
    const html = readFileSync(DIST_HTML, 'utf8');
    expect(html).toMatch(/\.dir-dino-tab\.active\s*\{\s*[^}]*background:\s*currentColor/);
    expect(html).toContain('.dir-dino-tab.active .dir-dino-icon');
  });
});

describe('pocantico-hills · course-file downloads', () => {
  const DIST_DATA = join(ROOT, 'dist', 'maps', 'pocantico-hills', 'data');

  it('publishes both per-distance GPX files into dist/.../data', () => {
    for (const id of ['marathon', 'half-marathon']) {
      const published = join(DIST_DATA, id + '.gpx');
      expect(existsSync(published)).toBe(true);
      // The published file is the real GPX, byte-for-byte the source.
      const src = readFileSync(join(DATA_DIR, id + '.gpx'), 'utf8');
      expect(readFileSync(published, 'utf8')).toBe(src);
    }
  });

  it('does NOT publish internal artifacts (turns, profiles, weather, tbt)', () => {
    for (const name of [
      'marathon-turns.geojson', 'marathon-profile.json',
      'half-marathon-turns.geojson', 'weather.json', 'marathon-tbt.md',
    ]) {
      expect(existsSync(join(DIST_DATA, name))).toBe(false);
    }
  });

  it('renders one download card per distance, each linking the real GPX', () => {
    const html = readFileSync(DIST_HTML, 'utf8');
    // One working GPX anchor per distance, with the watch-friendly
    // download filename namespaced by slug.
    expect(html).toContain('href="data/marathon.gpx" download="pocantico-hills-marathon.gpx"');
    expect(html).toContain('href="data/half-marathon.gpx" download="pocantico-hills-half-marathon.gpx"');
    // Each card is labelled by its distance + format.
    expect(html).toContain('Marathon GPX');
    expect(html).toContain('Half Marathon GPX');
    // The old single broken geojson link must be gone.
    expect(html).not.toContain('href="data/marathon.geojson"');
    expect(html).not.toContain('{{DOWNLOAD_CARDS}}');
  });
});

describe('pocantico-hills · embed build', () => {
  const EMBED_HTML = join(ROOT, 'dist', 'embed', 'pocantico-hills', 'index.html');

  it('embed builds with pocantico-hills in the editorial-races CSS allowlist', () => {
    expect(existsSync(EMBED_HTML)).toBe(true);
    const html = readFileSync(EMBED_HTML, 'utf8');
    // The in-map .profile-section is hidden for editorial-format
    // embeds so it doesn't crowd out the directions panel. Pocantico
    // is editorial-format — embed.css now lists it.
    expect(html).toMatch(/body\.embed-mode\.race-pocantico-hills #mapView \.profile-section/);
    // Same allowlist hides the Map/Sim tabs row (sim is only
    // wired for legacy maps via view-switch.js, which editorial
    // skipSharedJs maps don't ship).
    expect(html).toMatch(/body\.embed-mode\.race-pocantico-hills \.embed-tabs/);
  });
});

describe('pocantico-hills · regression — other races unaffected', () => {
  it('Gran Fondo Badlands still uses km in its editorial aid table', () => {
    const gfbPath = join(ROOT, 'dist', 'maps', 'gran-fondo-badlands', 'index.html');
    if (!existsSync(gfbPath)) return; // build hasn't covered this map; skip
    const html = readFileSync(gfbPath, 'utf8');
    expect(html).toContain('aid-table__mile">Km<');
  });

  it('Wild Goose still uses Mile in the editorial aid table', () => {
    const wgPath = join(ROOT, 'dist', 'maps', 'wild-goose', 'index.html');
    if (!existsSync(wgPath)) return;
    const html = readFileSync(wgPath, 'utf8');
    expect(html).toContain('aid-table__mile">Mile<');
  });
});
